# ref: https://github.com/actions/runner-images
name: amd64 Linux

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    name: Linux • Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check python
        run: python3 --version
      - name: Install
        run: python3 -m pip install -U --user "ortools==9.5.*"
      - name: Test
        run: python3 basic_example.py
